name: Update Rublacklist IPv4 (aggregate /24)

on:
  schedule:
    - cron: '0 */3 * * *'  # запуск каждые 3 часа
  workflow_dispatch:         # запуск вручную из UI GitHub
  push:
    branches:
      - main

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - run: python -m pip install --upgrade pip requests

      - name: Run update script
        run: python update_rbl.py

      - name: Commit & push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add rublacklist_ipv4_raw.txt rublacklist_ipv4_aggregated24.txt || true
          if ! git diff --staged --quiet && ! git diff --quiet; then
            git commit -m "Auto-update: refresh aggregated /24 lists ($(date -u +"%Y-%m-%d %H:%M:%S UTC"))" || true
            git push origin HEAD:main
          else
            echo "No changes to commit"
